name: Publish npm package

on:
  push:
    branches:
      - main # 在主分支推送代码时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 更新到 v4 版本，使用最新的 checkout Action
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # 设置 Node.js 版本为 20
      - name: Print working directory
        run: echo "Current working directory: $(pwd)" # 打印当前工作目录
      - name: Install dependencies
        run: npm install # 安装依赖项
      - name: Build
        run: npm run build # 构建项目
      - name: Publish to npm
        uses: actions/upload-artifact@v3 # 将构建后的文件上传到制品
        with:
          name: npm-package # 制品名称
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}
          npm publish # 发布 npm 包
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 你的 npm 访问令牌
