name: aave-interfaces

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build 
      - name: Login to npm  # 添加这一步
        run: npm adduser --registry https://registry.npmjs.org/ --always-auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to npm
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
